let a = 5;
let b = 10;
console.log(a + b);
console.log(a - b);
console.log(a * b);
console.log(a / b);
console.log(a % b);
console.log(a ** b);
console.log(a++);
console.log(a);
console.log(++a);
console.log(a);
console.log(a--);
console.log(a);
console.log(--a);
console.log(a);
console.log(a == b);
console.log(a != b);
console.log(a > b);
console.log(a < b);
console.log(a >= b);
console.log(a <= b);
console.log(a === b);
console.log(a !== b);

console.log(a > b && b < a);
console.log(a > b || b < a);
console.log(!(a > b));

console.log(a & b);
console.log(a | b);
console.log(a ^ b);
console.log(~a);
console.log(a << b);
console.log(a >> b);
